# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(607, 518)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setBaseSize(QtCore.QSize(1536, 864))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setBaseSize(QtCore.QSize(1536, 824))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setBaseSize(QtCore.QSize(1536, 824))
        self.splitter.setMidLineWidth(1336)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(5)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.ViewPort = QtWidgets.QWidget(self.splitter)
        self.ViewPort.setBaseSize(QtCore.QSize(1336, 824))
        self.ViewPort.setAcceptDrops(True)
        self.ViewPort.setAutoFillBackground(True)
        self.ViewPort.setObjectName("ViewPort")
        self.SideBar = QtWidgets.QWidget(self.splitter)
        self.SideBar.setMinimumSize(QtCore.QSize(150, 0))
        self.SideBar.setMaximumSize(QtCore.QSize(400, 16777215))
        self.SideBar.setBaseSize(QtCore.QSize(200, 824))
        self.SideBar.setAutoFillBackground(False)
        self.SideBar.setStyleSheet("QWidget {\n"
"    background: #181D31;\n"
"}")
        self.SideBar.setObjectName("SideBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.SideBar)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleFrame = QtWidgets.QWidget(self.SideBar)
        self.TitleFrame.setMinimumSize(QtCore.QSize(150, 40))
        self.TitleFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.TitleFrame.setObjectName("TitleFrame")
        self.ToolbarTitleLayout = QtWidgets.QVBoxLayout(self.TitleFrame)
        self.ToolbarTitleLayout.setContentsMargins(0, 0, 0, 0)
        self.ToolbarTitleLayout.setSpacing(0)
        self.ToolbarTitleLayout.setObjectName("ToolbarTitleLayout")
        self.Title = QtWidgets.QLabel(self.TitleFrame)
        self.Title.setMinimumSize(QtCore.QSize(150, 40))
        self.Title.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setStyleSheet("QLabel {\n"
"    color: #F0E9D2;\n"
"    background: #678983;\n"
"    border-bottom-left-radius: 5%;\n"
"    border-bottom-right-radius: 5%;\n"
"}")
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.ToolbarTitleLayout.addWidget(self.Title)
        self.verticalLayout.addWidget(self.TitleFrame)
        self.ModeFrame = QtWidgets.QFrame(self.SideBar)
        self.ModeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ModeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ModeFrame.setObjectName("ModeFrame")
        self.ModeFrameLayout = QtWidgets.QVBoxLayout(self.ModeFrame)
        self.ModeFrameLayout.setContentsMargins(10, 5, 10, 5)
        self.ModeFrameLayout.setSpacing(5)
        self.ModeFrameLayout.setObjectName("ModeFrameLayout")
        self.ExplorationTool = QtWidgets.QRadioButton(self.ModeFrame)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.ExplorationTool.setFont(font)
        self.ExplorationTool.setStyleSheet("QRadioButton {\n"
"    color: #F0E9D2;\n"
"}")
        self.ExplorationTool.setAutoRepeat(False)
        self.ExplorationTool.setAutoExclusive(True)
        self.ExplorationTool.setObjectName("ExplorationTool")
        self.ModeSelectionGroup = QtWidgets.QButtonGroup(MainWindow)
        self.ModeSelectionGroup.setObjectName("ModeSelectionGroup")
        self.ModeSelectionGroup.addButton(self.ExplorationTool)
        self.ModeFrameLayout.addWidget(self.ExplorationTool)
        self.SelectionTool = QtWidgets.QRadioButton(self.ModeFrame)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.SelectionTool.setFont(font)
        self.SelectionTool.setStyleSheet("QRadioButton {\n"
"    color: #F0E9D2;\n"
"}")
        self.SelectionTool.setAutoRepeat(False)
        self.SelectionTool.setAutoExclusive(True)
        self.SelectionTool.setObjectName("SelectionTool")
        self.ModeSelectionGroup.addButton(self.SelectionTool)
        self.ModeFrameLayout.addWidget(self.SelectionTool)
        self.verticalLayout.addWidget(self.ModeFrame)
        self.SliderFrame = QtWidgets.QFrame(self.SideBar)
        self.SliderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SliderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SliderFrame.setObjectName("SliderFrame")
        self.SlidersFrameLayout = QtWidgets.QVBoxLayout(self.SliderFrame)
        self.SlidersFrameLayout.setContentsMargins(10, 5, 10, 5)
        self.SlidersFrameLayout.setSpacing(5)
        self.SlidersFrameLayout.setObjectName("SlidersFrameLayout")
        self.brightness = QtWidgets.QLabel(self.SliderFrame)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.brightness.setFont(font)
        self.brightness.setStyleSheet("QLabel {\n"
"    color: #F0E9D2;\n"
"}")
        self.brightness.setAlignment(QtCore.Qt.AlignCenter)
        self.brightness.setObjectName("brightness")
        self.SlidersFrameLayout.addWidget(self.brightness)
        self.SliderZoom = QtWidgets.QSlider(self.SliderFrame)
        self.SliderZoom.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: #678983;\n"
"    border: 1px solid #F0E9D2;\n"
"    margin: -2px 0;\n"
"    border-radius: 3px;\n"
"}")
        self.SliderZoom.setOrientation(QtCore.Qt.Horizontal)
        self.SliderZoom.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.SliderZoom.setObjectName("SliderZoom")
        self.SlidersFrameLayout.addWidget(self.SliderZoom)
        self.zoom = QtWidgets.QLabel(self.SliderFrame)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.zoom.setFont(font)
        self.zoom.setStyleSheet("QLabel {\n"
"    color: #F0E9D2;\n"
"}")
        self.zoom.setAlignment(QtCore.Qt.AlignCenter)
        self.zoom.setObjectName("zoom")
        self.SlidersFrameLayout.addWidget(self.zoom)
        self.SliderZoom_2 = QtWidgets.QSlider(self.SliderFrame)
        self.SliderZoom_2.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: #678983;\n"
"    border: 1px solid #F0E9D2;\n"
"    margin: -2px 0;\n"
"    border-radius: 3px;\n"
"}")
        self.SliderZoom_2.setOrientation(QtCore.Qt.Horizontal)
        self.SliderZoom_2.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.SliderZoom_2.setObjectName("SliderZoom_2")
        self.SlidersFrameLayout.addWidget(self.SliderZoom_2)
        self.verticalLayout.addWidget(self.SliderFrame)
        self.CheckBoxFrame = QtWidgets.QFrame(self.SideBar)
        self.CheckBoxFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CheckBoxFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CheckBoxFrame.setObjectName("CheckBoxFrame")
        self.CheckBoxesFrameLayout = QtWidgets.QVBoxLayout(self.CheckBoxFrame)
        self.CheckBoxesFrameLayout.setContentsMargins(10, 5, 10, 5)
        self.CheckBoxesFrameLayout.setSpacing(5)
        self.CheckBoxesFrameLayout.setObjectName("CheckBoxesFrameLayout")
        self.Layer1 = QtWidgets.QCheckBox(self.CheckBoxFrame)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.Layer1.setFont(font)
        self.Layer1.setStyleSheet("QCheckBox {\n"
"    color: #F0E9D2;\n"
"}")
        self.Layer1.setObjectName("Layer1")
        self.LayerManipulationGroup = QtWidgets.QButtonGroup(MainWindow)
        self.LayerManipulationGroup.setObjectName("LayerManipulationGroup")
        self.LayerManipulationGroup.setExclusive(False)
        self.LayerManipulationGroup.addButton(self.Layer1)
        self.CheckBoxesFrameLayout.addWidget(self.Layer1)
        self.Layer2 = QtWidgets.QCheckBox(self.CheckBoxFrame)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.Layer2.setFont(font)
        self.Layer2.setStyleSheet("QCheckBox {\n"
"    color: #F0E9D2;\n"
"}")
        self.Layer2.setObjectName("Layer2")
        self.LayerManipulationGroup.addButton(self.Layer2)
        self.CheckBoxesFrameLayout.addWidget(self.Layer2)
        self.Lock1 = QtWidgets.QCheckBox(self.CheckBoxFrame)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.Lock1.setFont(font)
        self.Lock1.setStyleSheet("QCheckBox {\n"
"    color: #F0E9D2;\n"
"}")
        self.Lock1.setObjectName("Lock1")
        self.LayerManipulationGroup.addButton(self.Lock1)
        self.CheckBoxesFrameLayout.addWidget(self.Lock1)
        self.Lock2 = QtWidgets.QCheckBox(self.CheckBoxFrame)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.Lock2.setFont(font)
        self.Lock2.setStyleSheet("QCheckBox {\n"
"    color: #F0E9D2;\n"
"}")
        self.Lock2.setObjectName("Lock2")
        self.LayerManipulationGroup.addButton(self.Lock2)
        self.CheckBoxesFrameLayout.addWidget(self.Lock2)
        self.verticalLayout.addWidget(self.CheckBoxFrame)
        self.ButtonFrame = QtWidgets.QFrame(self.SideBar)
        self.ButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonFrame.setObjectName("ButtonFrame")
        self.ButtonsFrameLayout = QtWidgets.QVBoxLayout(self.ButtonFrame)
        self.ButtonsFrameLayout.setContentsMargins(10, 5, 10, 5)
        self.ButtonsFrameLayout.setSpacing(10)
        self.ButtonsFrameLayout.setObjectName("ButtonsFrameLayout")
        self.ResetCamera = QtWidgets.QPushButton(self.ButtonFrame)
        self.ResetCamera.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.ResetCamera.setFont(font)
        self.ResetCamera.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background:#F0E9D2;\n"
"    color: #181D31;\n"
"}\n"
"\n"
"\n"
"QPushButton::hover {\n"
"    background: #E6DDC4;\n"
"}")
        self.ResetCamera.setObjectName("ResetCamera")
        self.ButtonsFrameLayout.addWidget(self.ResetCamera)
        self.ResetPos1 = QtWidgets.QPushButton(self.ButtonFrame)
        self.ResetPos1.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.ResetPos1.setFont(font)
        self.ResetPos1.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background:#F0E9D2;\n"
"    color: #181D31;\n"
"}\n"
"\n"
"\n"
"QPushButton::hover {\n"
"    background: #E6DDC4;\n"
"}")
        self.ResetPos1.setObjectName("ResetPos1")
        self.ButtonsFrameLayout.addWidget(self.ResetPos1)
        self.ResetPos2 = QtWidgets.QPushButton(self.ButtonFrame)
        self.ResetPos2.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.ResetPos2.setFont(font)
        self.ResetPos2.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background:#F0E9D2;\n"
"    color: #181D31;\n"
"}\n"
"\n"
"\n"
"QPushButton::hover {\n"
"    background: #E6DDC4;\n"
"}")
        self.ResetPos2.setObjectName("ResetPos2")
        self.ButtonsFrameLayout.addWidget(self.ResetPos2)
        self.verticalLayout.addWidget(self.ButtonFrame)
        self.RunFrame = QtWidgets.QFrame(self.SideBar)
        self.RunFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RunFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RunFrame.setObjectName("RunFrame")
        self.RunFrameLayout = QtWidgets.QVBoxLayout(self.RunFrame)
        self.RunFrameLayout.setContentsMargins(10, 5, 10, 5)
        self.RunFrameLayout.setSpacing(5)
        self.RunFrameLayout.setObjectName("RunFrameLayout")
        self.Analysis = QtWidgets.QPushButton(self.RunFrame)
        self.Analysis.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Analysis.setFont(font)
        self.Analysis.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background:#678983;\n"
"    color: #F0E9D2;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background:#F0E9D2;\n"
"    color: #181D31;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background: #E6DDC4;\n"
"    color: #181D31;\n"
"}")
        self.Analysis.setObjectName("Analysis")
        self.RunFrameLayout.addWidget(self.Analysis)
        self.Return = QtWidgets.QPushButton(self.RunFrame)
        self.Return.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Return.setFont(font)
        self.Return.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background:#F0E9D2;\n"
"    color: #181D31;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: #E6DDC4;\n"
"}")
        self.Return.setObjectName("Return")
        self.RunFrameLayout.addWidget(self.Return)
        self.verticalLayout.addWidget(self.RunFrame)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 607, 20))
        self.menubar.setMinimumSize(QtCore.QSize(0, 20))
        self.menubar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMinimumSize(QtCore.QSize(0, 20))
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_file = QtWidgets.QAction(MainWindow)
        self.actionLoad_file.setObjectName("actionLoad_file")
        self.actionSave_file = QtWidgets.QAction(MainWindow)
        self.actionSave_file.setObjectName("actionSave_file")
        self.menuFile.addAction(self.actionLoad_file)
        self.menuFile.addAction(self.actionSave_file)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ExplorationTool, self.SelectionTool)
        MainWindow.setTabOrder(self.SelectionTool, self.SliderZoom)
        MainWindow.setTabOrder(self.SliderZoom, self.SliderZoom_2)
        MainWindow.setTabOrder(self.SliderZoom_2, self.Layer1)
        MainWindow.setTabOrder(self.Layer1, self.Layer2)
        MainWindow.setTabOrder(self.Layer2, self.Lock1)
        MainWindow.setTabOrder(self.Lock1, self.Lock2)
        MainWindow.setTabOrder(self.Lock2, self.ResetCamera)
        MainWindow.setTabOrder(self.ResetCamera, self.ResetPos1)
        MainWindow.setTabOrder(self.ResetPos1, self.ResetPos2)
        MainWindow.setTabOrder(self.ResetPos2, self.Analysis)
        MainWindow.setTabOrder(self.Analysis, self.Return)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Toolbar"))
        self.ExplorationTool.setText(_translate("MainWindow", "Exploration tool"))
        self.SelectionTool.setText(_translate("MainWindow", "Selection tool"))
        self.brightness.setText(_translate("MainWindow", "Brightness"))
        self.zoom.setText(_translate("MainWindow", "Zoom"))
        self.Layer1.setText(_translate("MainWindow", "Hide layer 1"))
        self.Layer2.setText(_translate("MainWindow", "Hide layer 2"))
        self.Lock1.setText(_translate("MainWindow", "Lock layer 1"))
        self.Lock2.setText(_translate("MainWindow", "Lock layer 2"))
        self.ResetCamera.setText(_translate("MainWindow", "Reset Camera"))
        self.ResetPos1.setText(_translate("MainWindow", "Reset Position 1"))
        self.ResetPos2.setText(_translate("MainWindow", "Reset Position 2"))
        self.Analysis.setText(_translate("MainWindow", "Run analysis"))
        self.Return.setText(_translate("MainWindow", "Return"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionLoad_file.setText(_translate("MainWindow", "Load file"))
        self.actionSave_file.setText(_translate("MainWindow", "Save file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
