# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patientDataCollection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import QObject
from PySide2.QtWidgets import QFileDialog, QMainWindow
from MainEditingPage import Ui_MainEditingPage

class Ui_PatientDataCollectionPage(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.please_input_patient_data_label = QtWidgets.QLabel(self.centralwidget)
        self.please_input_patient_data_label.setGeometry(QtCore.QRect(190, 20, 820, 95))
        self.please_input_patient_data_label.setObjectName("please_input_patient_data_label")
        big_bold_font = QtGui.QFont()
        big_bold_font.setPointSize(35)
        big_bold_font.setBold(True)
        big_bold_font.setWeight(75)
        big_bold_font.setFamily("Bahnschrift Light")
        self.please_input_patient_data_label.setFont(big_bold_font)

        label_font = QtGui.QFont()
        label_font.setPointSize(20)
        label_font.setFamily("Bahnschrift Light")

        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(30, 150, 200, 50))
        self.name_label.setObjectName("name_label")
        self.name_label.setFont(label_font)

        self.age_label = QtWidgets.QLabel(self.centralwidget)
        self.age_label.setGeometry(QtCore.QRect(30, 220, 200, 50))
        self.age_label.setObjectName("age_label")
        self.age_label.setFont(label_font)

        self.medical_history_label = QtWidgets.QLabel(self.centralwidget)
        self.medical_history_label.setGeometry(QtCore.QRect(30, 290, 300, 50))
        self.medical_history_label.setObjectName("medical_history_label")
        self.medical_history_label.setFont(label_font)

        self.pain_complaint_label = QtWidgets.QLabel(self.centralwidget)
        self.pain_complaint_label.setGeometry(QtCore.QRect(30, 360, 300, 50))
        self.pain_complaint_label.setObjectName("pain_complaint_label")
        self.pain_complaint_label.setFont(label_font)

        self.dental_history_label = QtWidgets.QLabel(self.centralwidget)
        self.dental_history_label.setGeometry(QtCore.QRect(30, 430, 300, 50))
        self.dental_history_label.setObjectName("dental_history_label")
        self.dental_history_label.setFont(label_font)

        self.sociobehavioral_history_label = QtWidgets.QLabel(self.centralwidget)
        self.sociobehavioral_history_label.setGeometry(QtCore.QRect(30, 500, 430, 50))
        self.sociobehavioral_history_label.setObjectName("sociobehavioral_history_label")
        self.sociobehavioral_history_label.setFont(label_font)

        self.financial_resources_label = QtWidgets.QLabel(self.centralwidget)
        self.financial_resources_label.setGeometry(QtCore.QRect(30, 570, 370, 50))
        self.financial_resources_label.setObjectName("financial_resources_label")
        self.financial_resources_label.setFont(label_font)

        self.upper_jaw_scan_label = QtWidgets.QLabel(self.centralwidget)
        self.upper_jaw_scan_label.setGeometry(QtCore.QRect(30, 640, 300, 50))
        self.upper_jaw_scan_label.setObjectName("upper_jaw_scan_label")
        self.upper_jaw_scan_label.setFont(label_font)

        self.lower_jaw_scan_label = QtWidgets.QLabel(self.centralwidget)
        self.lower_jaw_scan_label.setGeometry(QtCore.QRect(30, 710, 300, 50))
        self.lower_jaw_scan_label.setObjectName("lower_jaw_scan_label")
        self.lower_jaw_scan_label.setFont(label_font)

        self.name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.name_input.setGeometry(QtCore.QRect(470, 150, 700, 50))
        self.name_input.setObjectName("name_input")
        self.name_input.setFont(label_font)

        self.age_input = QtWidgets.QSpinBox(self.centralwidget)
        self.age_input.setGeometry(QtCore.QRect(470, 220, 100, 50))
        self.age_input.setMaximum(120)
        self.age_input.setObjectName("age_input")
        self.age_input.setFont(label_font)

        combo_font = QtGui.QFont()
        combo_font.setPointSize(9)
        combo_font.setFamily("Bahnschrift Light")

        self.medical_history_input = QtWidgets.QComboBox(self.centralwidget)
        self.medical_history_input.setGeometry(QtCore.QRect(470, 290, 700, 50))
        self.medical_history_input.setObjectName("medical_history_input")
        self.medical_history_input.addItem("gastric disorders")
        self.medical_history_input.addItem("eating disorders")
        self.medical_history_input.addItem("erosive medications/supplements")
        self.medical_history_input.addItem("reduced salivary flow")
        self.medical_history_input.addItem("psychological conditions")
        self.medical_history_input.addItem("chronic alcoholism")
        self.medical_history_input.addItem("radiotherapy to head and neck region")
        self.medical_history_input.addItem("none of the above")
        self.medical_history_input.setFont(combo_font)

        self.pain_complaint_input = QtWidgets.QComboBox(self.centralwidget)
        self.pain_complaint_input.setGeometry(QtCore.QRect(470, 360, 700, 50))
        self.pain_complaint_input.setObjectName("pain_complaint_input")
        self.pain_complaint_input.addItem("sensitivity and/or pain")
        self.pain_complaint_input.addItem("functional problems (difficulty chewing and eating)")
        self.pain_complaint_input.addItem("deterioration of aesthetic appearance (compromised dental attractiveness)")
        self.pain_complaint_input.addItem("fast progress of the tooth wear process after a period of monitoring")
        self.pain_complaint_input.addItem("wear atypical for the age of the patient")
        self.pain_complaint_input.addItem("crumbling of dental hard tissue and restorations, threatening the "
                                          "integrity of teeth")
        self.pain_complaint_input.addItem("etiological factors not influenceable")
        self.pain_complaint_input.addItem("surfaces that are included in occlusion and articulation, leading to the "
                                          "loss of VDO")
        self.pain_complaint_input.addItem("the condition of the saliva ")
        self.pain_complaint_input.addItem("phonetic impairment")
        self.pain_complaint_input.addItem("none of the above")
        self.pain_complaint_input.setFont(combo_font)

        self.dental_history_input = QtWidgets.QComboBox(self.centralwidget)
        self.dental_history_input.setGeometry(QtCore.QRect(470, 430, 700, 50))
        self.dental_history_input.setObjectName("dental_history_input")

        self.sociobehavioral_history_input = QtWidgets.QComboBox(self.centralwidget)
        self.sociobehavioral_history_input.setGeometry(QtCore.QRect(470, 500, 700, 50))
        self.sociobehavioral_history_input.setObjectName("sociobehavioral_history_input")

        self.financial_resources_input = QtWidgets.QComboBox(self.centralwidget)
        self.financial_resources_input.setGeometry(QtCore.QRect(470, 570, 700, 50))
        self.financial_resources_input.setObjectName("financial_resources_input")

        self.choose_upper_jaw_scan_button = QtWidgets.QPushButton(self.centralwidget)
        self.choose_upper_jaw_scan_button.setGeometry(QtCore.QRect(470, 640, 300, 50))
        self.choose_upper_jaw_scan_button.setObjectName("choose_upper_jaw_scan_button")

        self.choose_lower_jaw_scan_button = QtWidgets.QPushButton(self.centralwidget)
        self.choose_lower_jaw_scan_button.setGeometry(QtCore.QRect(470, 710, 300, 50))
        self.choose_lower_jaw_scan_button.setObjectName("choose_lower_jaw_scan_button")

        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(1050, 770, 100, 50))
        self.next_button.setObjectName("next_button")
        self.next_button.setFont(label_font)
        self.next_button.setStyleSheet("QPushButton {\n"
                                    "    border-radius: 5px;\n"
                                    "    background:#678983;\n"
                                    "    color: #F0E9D2;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton::hover {\n"
                                    "    background:#F0E9D2;\n"
                                    "    color: #181D31;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton::pressed {\n"
                                    "    background: #E6DDC4;\n"
                                    "    color: #181D31;\n"
                                    "}")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.please_input_patient_data_label.setText(_translate("MainWindow", "Please input patient data:"))
        self.name_label.setText(_translate("MainWindow", "Name:"))
        self.age_label.setText(_translate("MainWindow", "Age:"))
        self.medical_history_label.setText(_translate("MainWindow", "Medical History:"))
        self.pain_complaint_label.setText(_translate("MainWindow", "Pain Complaint:"))
        self.dental_history_label.setText(_translate("MainWindow", "Dental History:"))
        self.sociobehavioral_history_label.setText(_translate("MainWindow", "Sociobehavioral History:"))
        self.financial_resources_label.setText(_translate("MainWindow", "Financial Resources:"))
        self.upper_jaw_scan_label.setText(_translate("MainWindow", "Upper Jaw Scan:"))
        self.lower_jaw_scan_label.setText(_translate("MainWindow", "Lower Jaw Scan:"))
        self.choose_upper_jaw_scan_button.setText(_translate("MainWindow", "Choose an upper jaw scan file..."))
        self.choose_lower_jaw_scan_button.setText(_translate("MainWindow", "Choose a lower jaw scan file..."))
        self.next_button.setText(_translate("MainWindow", "Next"))

class MainWindow(QMainWindow, Ui_PatientDataCollectionPage):
    def __init__(self):
        Ui_PatientDataCollectionPage.__init__(self)
        Ui_MainEditingPage.__init__(self)
        QMainWindow.__init__(self)
        self.uiWindow1 = Ui_PatientDataCollectionPage()
        self.uiWindow2 = Ui_MainEditingPage()
        self.startPatientDataCollectionPage()

    def startPatientDataCollectionPage(self):
        self.uiWindow1.setupUi(self)
        self.uiWindow1.choose_upper_jaw_scan_button.clicked.connect(self.choose_file)
        self.uiWindow1.choose_lower_jaw_scan_button.clicked.connect(self.choose_file)
        self.uiWindow1.next_button.clicked.connect(self.startMainEditingPage)

    def tr(self, text):
        return QObject.tr(self, text)

    def choose_file(self):
        fileName = QFileDialog.getOpenFileName(self,
                                                self.tr("Open File"), self.tr("~/Desktop/"), self.tr("3D Files (*.ply *.stl)"));

    def startMainEditingPage(self):
        self.uiWindow2.setupUi(self)
        self.uiWindow2.Return.clicked.connect(self.startPatientDataCollectionPage)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = MainWindow()
    main_window.show()
    sys.exit(app.exec_())
